### ISSUE TITLE
Create and understand fake GeoJson formatted data

### ISSUE THREAD

**Issue by sperez8** [PeaceGeeksSociety/prj-cepo-sms#10]

**Comment by PeaceGeeks** [comment]
Hi @sperez8 - isn't this done now?

**Comment by sperez8** [comment]
This item is for the enhanced version of the viz which is a work in progress and will be part of the second release.

**Comment by mackh** [comment]
hi there - http://www.cepo-southsudan.org/geojson/incident-reports  there is JSON generated directly, not sure what you are doing to generate fake JSON but this might be helpful

**Comment by sperez8** [comment]
Hi mackh, thanks for the resource!

Originally I intended to create a viz separately from the current map interface and then integrate it (which I thought would require making fake data to familiarize myslef with it) but I have to rethink this process. I am closing the issue and when I start working on revamping the current visualization I will create more up to date "todo" issues.
