### ISSUE TITLE
Connect components of viz using crossfilter

### ISSUE THREAD

**Issue by sperez8** [PeaceGeeksSociety/prj-cepo-sms#14]
Given the current draft of the data viz built by Devan, need to enable interactivity by adding cross-filter

**Comment by PeaceGeeks** [comment]
Hi @sperez8 - is this done now?

**Comment by sperez8** [comment]
This item is for the enhanced version of the viz which is a work in progress and will be part of the second release.

**Comment by PeaceGeeksProjects** [comment]
@sperez8 second release issues are moved to backlog not closed

**Comment by sperez8** [comment]
Agreed second release issues shouldn't be closed but I am rethinking how I am going to work with the second release and I don't think this item will be relevant in that new process.

**Comment by PeaceGeeksProjects** [comment]
Issue moved to [PeaceGeeksSociety/amani-sms #12](https://github.com/PeaceGeeksSociety/amani-sms/issues/12) via [**ZenHub.io**](https://www.zenhub.io/)
