### ISSUE TITLE
Add filters for Age, Health, etc.

### ISSUE THREAD

**Issue by sperez8** [PeaceGeeksSociety/prj-cepo-sms#16]

**Comment by PeaceGeeksProjects** [comment]
Reason for closing?

**Comment by sperez8** [comment]
Sorry by mistake! Got to excited while closing issues..

**Comment by PeaceGeeksProjects** [comment]
Issue moved to [PeaceGeeksSociety/amani-sms #13](https://github.com/PeaceGeeksSociety/amani-sms/issues/13) via [**ZenHub.io**](https://www.zenhub.io/)
