### ISSUE TITLE
format the map based viz to look like the mockup

### ISSUE THREAD

**Issue by sperez8** [PeaceGeeksSociety/prj-cepo-sms#17]
[CEPO-dataviz-mockup.pdf](https://github.com/PeaceGeeksSociety/CEPO-SMS/files/94600/CEPO-dataviz-mockup.pdf)

Once the core map viz is made, some styling will be needed to arrange things on an amani page.

Current guideline is the mockup created by Ren.

**Comment by PeaceGeeksProjects** [comment]
Please specify reason for closing

**Comment by sperez8** [comment]
Sorry by mistake! Got to excited while closing issues..

**Comment by PeaceGeeksProjects** [comment]
Issue moved to [PeaceGeeksSociety/amani-sms #14](https://github.com/PeaceGeeksSociety/amani-sms/issues/14) via [**ZenHub.io**](https://www.zenhub.io/)
