### ISSUE TITLE
Integrate map based viz into amani

### ISSUE THREAD

**Issue by sperez8** [PeaceGeeksSociety/prj-cepo-sms#18]

**Comment by PeaceGeeksProjects** [comment]
@sperez8 why did you close this... it was on backlog i.e. to be done on a later version

**Comment by sperez8** [comment]
I closed it because I am going to rethink how to revamp the mapviz and this issue doesn't accurately describe a step in that process. We can keep it for now and when I lay out the work decide if it's still relevant or not.

**Comment by PeaceGeeksProjects** [comment]
Issue moved to [PeaceGeeksSociety/amani-sms #15](https://github.com/PeaceGeeksSociety/amani-sms/issues/15) via [**ZenHub.io**](https://www.zenhub.io/)
