### ISSUE TITLE
Develop tool for filtering and exporting Amani Map data into a CSV file

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/prj-cepo-sms#20]

**Comment by bensinjin** [comment]
This is up at http://dev.ceposms.peacegeeks.org/map-record-export (click
csv button at bottom of view to download)

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks Please review the site at  http://dev.ceposms.peacegeeks.org

This is my guess at what the final site will look like.  If satisfied, please close this issue and open a new one for @bensinjin to update the Live site accordingly.

**Comment by PeaceGeeksProjects** [comment]
Tool working and verified on Dev & Live site
