### ISSUE TITLE
create sketch of summary report and share with team

### ISSUE THREAD

**Issue by sperez8** [PeaceGeeksSociety/prj-cepo-sms#21]
Using the snapshots of the drawings from the hackathon, need to make a more formal sketch of what the summary report will look like.

**Comment by PeaceGeeksProjects** [comment]
See https://docs.google.com/document/d/12nNjY3rEoI4Gvca7Y2Anqom-2oYxMXYlJxGbEtDwOXQ
I think it meets the needs for Release 1
