### ISSUE TITLE
Develop tool for filtering and reporting from a CSV file

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/prj-cepo-sms#22]

**Comment by sperez8** [comment]
Tool consists of executables built using pysintaller and can be found in the google drive folder:

https://drive.google.com/drive/folders/0B28h1vTxVSuHbDdnNl90QjRNQTA

Readme has been updated with instructions to run the executables.

**Comment by sperez8** [comment]
Note that the tool currently builds 2 out of 6 graphics, however I have closed this issue to reflect the fact that the architecture of the tool works and that additional graphics can be implemented over time.
