### ISSUE TITLE
Map Filter labels not displaying on content for for Amani Admins

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/prj-cepo-sms#26]
The labels for Map Filters #1 and #2 seem to be missing. Can you add them in and make them stack like #3 and #4?

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks This just needs configuration...  I'll copy the labels from the Dev site.  Are these finalized?

**Comment by PeaceGeeks** [comment]
Filter #1 = Gender
Filter #2 = Health Status
Filter #3 = Age
Filter #4 = Violation Category

**Comment by PeaceGeeksProjects** [comment]
Closing this issue and replacing with 2 new ones for Map Filter labeling on the map record and submission nodes
