### ISSUE TITLE
map records output in cvs should be in tab delimited format

### ISSUE THREAD

**Issue by sperez8** [PeaceGeeksSociety/prj-cepo-sms#27]
I have been playing around with the map records outputted from the webpage and realized that the file format might cause problems later on. Specifically if a narrative contains a comma, then outputting the data in a CSV or Comma Separated Format might split the narrative into two pieces. 

I would suggest outputting the data in a tab delimited file.

Thoughts?

**Comment by PeaceGeeksProjects** [comment]
This is not an issue, each field is enclosed in "".  see below Commas in the date working just fine
"23114-PG-JK"," An elderly woman in a wheelchair was attacked.
 ","Tuesday, November 23, 2004 - 00:00","Female","Physically Disabled","45-50","Rape","Yes"
Closing this issue

**Comment by sperez8** [comment]
I am not sure I explained myself well. There are no issues outputting the map records in cvs format. The problem will come later when my script loads the cvs file and parses it. There are no more brackets "" in that case and every comma, including ones potentially in the narrative, will be used as a record delimiter.

Does that make sense?

**Comment by PeaceGeeksProjects** [comment]
I  C...  @bensinjin is this easy?

**Comment by bensinjin** [comment]
Out of the box it's not exactly easy to produce a tab separated file - I'm not sure I'm clear on why we need to? How are you parsing this @sperez8 ? Are you implying the "" will be removed from your version of the exported csv at parse time?

**Comment by bensinjin** [comment]
Will you be parsing it with js?

**Comment by PeaceGeeksProjects** [comment]
@sperez8 could you add a step in your process to 'Save As' tab delimited?  This would be a quick & dirty workaround...

**Comment by sperez8** [comment]
Nevermind. I was using a file that had been opened in Excel and where the brackets were gone. I know see what you mean by separating the fields by brackets. I can use this so it's not a problem.

> Out of the box it's not exactly easy to produce a tab separated file

In that case let's keep it as is. I can work with this.

Sorry for the confusion!
