### ISSUE TITLE
Map Filters Labels on Nodes in View & Edit Modes

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/prj-cepo-sms#28]
@bensinjin can you please do something about it quick

Map Record View page: Labels not in order and not showing the filter Name entered by the user.  Also move 3 & 4 above the Geolocation map below 1 & 2.
![28-1](https://cloud.githubusercontent.com/assets/16202351/12770945/dc1149fc-c9d9-11e5-8977-c113b34e9aee.jpg)

Map Record Edit page: Labels 3 & 4 rename and align with 1 & 2
![28-2](https://cloud.githubusercontent.com/assets/16202351/12771029/7e49caa0-c9da-11e5-9cb3-9c8d4a1682a2.jpg)

**Comment by bensinjin** [comment]
What do you mean renamed?

**Comment by PeaceGeeksProjects** [comment]
Renamed as in the top pic above.  Label should be what the admin put in like 1 & 2  in the bottom pic above (Gender & Health Status)

**Comment by bensinjin** [comment]
ok so I'm not going to hard code any labels as they change on a per project basis - I will look into altering the labels on the node view to the ones on config if those settings are set.

**Comment by PeaceGeeksProjects** [comment]
Agree,  I thought this is how you did it in Amani for filter 1 & 2...

**Comment by bensinjin** [comment]
Sorry there was some confusion around labels on create forms/edit forms/node view/map blocks - I'm just in the process of standardizing it across the board.

**Comment by bensinjin** [comment]
Ok this has been addressed see http://sms.cepo-southsudan.org/ for example.

**Comment by PeaceGeeksProjects** [comment]
Tx Ben...  Verified
