### ISSUE TITLE
In CSV file of map records, field titles are inconsistent

### ISSUE THREAD

**Issue by sperez8** [PeaceGeeksSociety/prj-cepo-sms#29]
Super minor bug.

In the header of the csv file, the 'f' in 'filter' is capitalized in some field headers and lowercase in others.

> "Title","Narrative","Date","Map filter #1","Map filter #2","Map Filter #3","Map Filter #4","Published"

I don't mind which one you choose but consistency in parsing is key!

**Comment by PeaceGeeksProjects** [comment]
@sperez8 These map to totally different words e.g. Gender, Health, Age, Category.  Can you please explain your difficulty?

**Comment by sperez8** [comment]
It's not so much a problem as it is an inconvenience. I can work around it, I just know by experience that inconsistency can cause problems down the road...

**Comment by PeaceGeeks** [comment]
what is the status of this?
