### ISSUE TITLE
Data Export file is not capturing all map records

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/prj-cepo-sms#31]
I run the export file, but only 4 records show up - there should be many more records being selected unless I understand something incorrectly.

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks works fine with me with Published = Yes or Any...  how did you set the filters? Did you click apply button?  I left the dates unspecified...

@bensinjin is the low limit of 'year' to 2013 intentional?

**Comment by PeaceGeeks** [comment]
This seems to be working now, or at least I cannot replicate the issue, so closing for now.

**Comment by PeaceGeeks** [comment]
We don't need to report on past records so the 2013 start time is not an issue.
