### ISSUE TITLE
There is no way to select 'off' the timeline slides once you have chosen a timeline slice

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/prj-cepo-sms#34]

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks Just refresh the page..

**Comment by PeaceGeeks** [comment]
![screen shot 2016-02-17 at 12 17 19 am](https://cloud.githubusercontent.com/assets/2263033/13091378/e0bdb3e0-d50b-11e5-911e-f2f639908699.png)

**Comment by sperez8** [comment]
One work around to effectively "removing the filter" is to simply select the entire timeline that way you are not filtering anything.

**Comment by PeaceGeeksProjects** [comment]
Issue moved to [PeaceGeeksSociety/amani-sms #7](https://github.com/PeaceGeeksSociety/amani-sms/issues/7) via [**ZenHub.io**](https://www.zenhub.io/)
