### ISSUE TITLE
Marker color does not appear to change for past records

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/prj-cepo-sms#35]
I set the color for women to red and the color for men to blue, but I can only see one record in blue. Is this because the others were past records? Can we set this to apply retroactively to all records?

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks it is because there IS only 1 male record...

**Comment by PeaceGeeksProjects** [comment]
Issue moved to [PeaceGeeksSociety/amani-sms #10](https://github.com/PeaceGeeksSociety/amani-sms/issues/10) via [**ZenHub.io**](https://www.zenhub.io/)
