### ISSUE TITLE
Enable users to 'Create Record' from SMS Submission

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/prj-cepo-sms#41]
For records where an SMS submission was received but not a Map Record

**Comment by PeaceGeeks** [comment]
Node

**Comment by PeaceGeeks** [comment]
Also enable users to access related SMS submission from Map record

**Comment by PeaceGeeksProjects** [comment]
Issue moved to [PeaceGeeksSociety/amani-sms #16](https://github.com/PeaceGeeksSociety/amani-sms/issues/16) via [**ZenHub.io**](https://www.zenhub.io/)
