### ISSUE TITLE
ACCESS DENIED

### ISSUE THREAD

**Issue by jamesbilal** [PeaceGeeksSociety/prj-cepo-sms#42]
MAP RECORD: 
- Restricted access -
STATUS: 
Map Record Needs Review
SMS MESSAGE: 
{"message":"050116 CEPO jb wau m h 13 s a man was ...","message_id":"2b084271-fec2-4362-ae3b-24a5101d2ebf","secret":"12345678","device_id":"","from":"+254703664002","sent_to":"","sent_timestamp":"1455690740000"}
ERRORS: 
There was a problem with the Location - ensure the value exist in your sms configuration, There was a problem with Filter 1 - ensure the value exist in your sms configuration, There was a problem with Filter 3 - ensure the value exist in your sms configuration, There was a problem with Filter 4 - ensure the value exist in your sms configuration

**Comment by PeaceGeeksProjects** [comment]
Why did you reopen this... Please ask Renee to explain...

**Comment by PeaceGeeks** [comment]
Magdi - do not close a ticket until you have clarified with me please. We
ran up against this issue again.




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad

**Comment by PeaceGeeks** [comment]
James - an Amani Admin - is at the Admin view, and he tries to click on a Map Record to view the record but he gets the Access Denied message. Also, from the SMS Submission page, the Map Record shows as 'Restricted Access' as per the screenshot below. I believe he was choosing the second record from the top

![screen shot 2016-02-17 at 9 39 15 am](https://cloud.githubusercontent.com/assets/2263033/13103519/009922d8-d568-11e5-91c2-0619bf86d5c3.png)

![screen shot 2016-02-17 at 10 42 43 am](https://cloud.githubusercontent.com/assets/2263033/13103528/0e33bf5c-d568-11e5-8110-2ea6d61cf89d.png)

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks you can always re-open it.

It was missing filter values and was not published  I added the missing values all is well now.

**Comment by PeaceGeeks** [comment]
STOP closing this Magdi. THIS is presently a problem. See attachment. 

https://docs.google.com/a/cepo-southsudan.org/document/d/1Yc4Dm6E1ApkDFWTELgUtvRYOcZ_HdJm_ILDukAPw-Zo/edit?usp=sharing

**Comment by PeaceGeeks** [comment]
@bensinjin - can we have a link from the SMS Submission to the Map Record AND vice versa? 

Also, from a workflow perspective, it would really be idea if users could create a new Map Record from the SMS Submission node, by having the new blank node open in a separate window/ tab. Sometimes Map Records don't get created so the user will have to create the new Map Record from the SMS Submission. I would be ideal if they can see both at the same time

**Comment by PeaceGeeks** [comment]
To clarify since it seems Magdi didn't understand the issue, the user is seeing 'Restricted Access' when the click to View the record. They are actually able to edit, but if they view the record, they can't click the link to the corresponding Map Record.

**Comment by bensinjin** [comment]
@PeaceGeeks I did fix this access denied issue
![screen shot 2016-02-18 at 2 46 41 pm](https://cloud.githubusercontent.com/assets/3228323/13160812/b7cc810c-d64e-11e5-98d0-70f2ab5f43be.png)

(this is me logged in as my amani admin user) - As it stands currently I'm quite deep into another project and don't have time to implement the improvements. I'll let you know when I have some capacity.

**Comment by PeaceGeeks** [comment]
Ok thanks Ben




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks 
1st, I did NOT close th eissue, you just had not re-opened it :)
2nd, I think I do understand the issue well since I offered a solution:
       a. fill in all filter fields ( and any missing mandatory fields e.g. date)
       b. Set published to yes
I will let you close the issue once you verify that...

**Comment by PeaceGeeksProjects** [comment]
Issue moved to [PeaceGeeksSociety/amani-sms #9](https://github.com/PeaceGeeksSociety/amani-sms/issues/9) via [**ZenHub.io**](https://www.zenhub.io/)
