### ISSUE TITLE
Create training documentation for SMS reporting tool

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/prj-cepo-sms#8]
Creating tool documentation and training for SMS tool

**Comment by PeaceGeeksProjects** [comment]
will put on the drive

**Comment by PeaceGeeks** [comment]
Document created and can be viewed here https://docs.google.com/document/d/1sjTGC2s8dMbCY781_yZa-HkpzK4ht66tdDer5HuTWkE/edit?usp=sharing
